"""mahasiswa

Revision ID: 52b5a4dadb65
Revises: 
Create Date: 2025-01-03 21:47:35.880190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b5a4dadb65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_mahasiswa',
    sa.Column('npm', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=230), nullable=False),
    sa.Column('tgl_lahir', sa.Date(), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('npm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_mahasiswa')
    # ### end Alembic commands ###
